apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7RkdcHSw+Azhz/c=,iv:Dnc8NX/J4RZ6Z08vAruwUYzdsE3pFGvsOWbFX2sTD0Y=,tag:Cu/FBkQqkyHZaODJlhjdjw==,type:str]
sops:
  age:
    - recipient: age1jey2a474ad8fxzykye394p0l9c5n05tnd7gv2q3xtvh3hkulwahqje4ld2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Nkx6VTc4UUY2R29OK1RT
        YUlYWHo2L1JqamVFcnEyV0RYSnFlSktGOWh3CmUyeFYwa0QzY3BnenhKK2ZFTDZw
        T1NOZExRVDV1SittSEgwVUJDRTdKMEUKLS0tIFBmSWlMd0Y1SEdBQmc3WXczUSt2
        NVBlVU1qMlhoS1g4MVcrL1hYcEliOFUK4/ONiOAoE+r6I8XPdV0uthPb3DWO8kq6
        FsVt71aPSyqTW/6r9/Jcv1IQ2KVM+29QKgsVYOGV2RQuSi0X7n7T3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T00:07:46Z"
  mac: ENC[AES256_GCM,data:NrXLHOo2kw29QC8hjVk2cVnPTJyDmNNUeRhssIFkeD30pHlk9Qp48dbmp3FpSQeMWO6/ep1rn99tB1kgJ0govjmRNTsx8lX9PKFDWZcbyBJkvqEdtbiWhaT3QSWIfiIxu8Kv4weuAsjdP9RJ9fsNnbm650+wuKsrJ9GM6STog8E=,iv:wYrduDM5VfQ64NIIQXKLI/eGomIB2GRdOkohdz6S29s=,tag:M6O4clqrwOphUGuGFo7g6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
